name: ci

on:
  push:

concurrency:
  group: banana
  cancel-in-progress: true

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          check_filenames: true
          check_hidden: true

  lint-docker-compose-file:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup .env
        run: |
          if ! cp -a .env.example .env; then exit 255; fi
      - name: lint docker-compose file
        run: docker-compose config

  testing:
    name: run docker-compose
    needs: [codespell, linting]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: run test
        run: |
          .github/tests.sh
